version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smartpot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: smartpot
      POSTGRES_PASSWORD: smartpotpassword
      POSTGRES_DB: smartpot
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - smartpot-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartpot-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DATABASE_URL: postgres://smartpot:smartpotpassword@postgres:5432/smartpot
      JWT_SECRET: your-secret-key-here
      NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - smartpot-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartpot-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - smartpot-network

networks:
  smartpot-network:
    driver: bridge

volumes:
  postgres-data:
