version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smartpot-postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smartpot-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: smartpot-backend-prod
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - smartpot-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=${API_URL}
    container_name: smartpot-frontend-prod
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - smartpot-network

networks:
  smartpot-network:
    driver: bridge

volumes:
  postgres-data:
